import * as crypto from "crypto";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

// MVP1: 実 Claude Code セッション (.jsonl) を読み、user レベルの Fork 木を
// ノードモデル（描画に必要な最小フィールド）へ変換する。
// 設計根拠は PROTOTYPES.md §6.4（S0 調査結果）を参照。

export interface GraphNode {
  id: string; // = レコードの uuid
  // メモ・ピンの永続キー（MVP4）。canonical key（timestamp+type+内容）の SHA-1 短縮ハッシュ。
  // id（canonical uuid）は「最初に読んだ個体」で決まりファイルの読み込み順に依存して変わり得るが、
  // canonical key は論理イベントの同一性そのものなので再読込・Fork 複製をまたいで安定する。
  key: string;
  parent: string | null; // = 最も近い user 祖先の uuid（無ければ null = ルート）
  lane: number; // 描画レーン（MVP1 は素朴割当。原則A/B は MVP2）
  prompt: string; // message.content のテキスト
  session?: string; // 所属セッション（= rec.sessionId）。MVP3 の再開で使う
  timestamp?: string; // 発話時刻（ISO 8601）。右パネルの「いつ」表示に使う（MVP6）
  memo?: string; // 保存済みメモ（拡張本体が globalState から付与。MVP4）
  pinned?: boolean; // ピン留め（同上）
  // 親からこのノードへの辺の途中で /compact（コンテキスト圧縮）が実行された印。
  // Webview は該当エッジに 2 重波線（チャートの省略記号 ≈）を重ねて描く
  compacted?: boolean;
}

// 1行ぶんの JSONL レコード（必要なものだけ緩く型付け）
interface RawRecord {
  type?: string;
  uuid?: string;
  parentUuid?: string | null;
  sessionId?: string;
  // ISO 8601。Fork で uuid/sessionId は振り直されるが timestamp は保存される（S1 §2）。
  // 例外: fork 地点の末端 1 件だけは Fork 実行時刻に再スタンプされる（S1 §10.2）→ 二次結合で補修
  timestamp?: string;
  message?: { content?: unknown };
  attachment?: unknown; // attachment レコードの本体（指紋計算に使う）
  subtype?: string; // system レコードの subtype（指紋計算に使う）
  promptId?: string; // user: 投入プロンプトの安定 ID。Fork コピー後も保存される（S1 §10.3）
  requestId?: string; // assistant: API 呼び出しの安定 ID。同上（1ターン複数行で共有される点に注意）
  // true = ハーネスのシステム挿入（人の発話ではない）。代表例は VS Code がセッション再開時に注入する
  // 「Continue from where you left off.」。テキストでは判別できないためフラグで除外する（JSONL-FORMAT.md §2.1）
  isMeta?: boolean;
  // system/compact_boundary レコードのみ: 圧縮直前の末尾レコードの uuid。
  // compact_boundary は parentUuid が null（鎖がここで切れる）ため、これで橋渡ししないと
  // /compact 以降のノードがルートに化けて別の木になってしまう
  logicalParentUuid?: string | null;
}

// Claude Code のプロジェクトフォルダ名はパスの英数字以外を "-" に置換したもの。
// 例: c:\Users\natum\Desktop\claude-app\fork-graph
//   → c--Users-natum-Desktop-claude-app-fork-graph
export function encodeProjectPath(fsPath: string): string {
  return fsPath.replace(/[^A-Za-z0-9]/g, "-");
}

function projectsRoot(): string {
  return path.join(os.homedir(), ".claude", "projects");
}

// 与えられたワークスペースパスに対応する projects/<encoded> ディレクトリを返す。
// 完全一致が無ければ大文字小文字無視で探す（ドライブレターの揺れ対策）。
// export は「表示中フォルダ ≠ ワークスペースのフォルダ」判定（別フォルダのチャットは CLI で開く）に使う。
export function resolveProjectDir(workspacePath: string): string | undefined {
  const root = projectsRoot();
  if (!fs.existsSync(root)) {
    return undefined;
  }
  const encoded = encodeProjectPath(workspacePath);
  const exact = path.join(root, encoded);
  if (fs.existsSync(exact)) {
    return exact;
  }
  const lower = encoded.toLowerCase();
  for (const name of fs.readdirSync(root)) {
    if (name.toLowerCase() === lower) {
      return path.join(root, name);
    }
  }
  return undefined;
}

// プロジェクトフォルダ内で最後に更新された .jsonl（＝直近のセッション）を選ぶ。
function latestSessionFile(projectDir: string): string | undefined {
  const files = fs
    .readdirSync(projectDir)
    .filter((f) => f.endsWith(".jsonl"))
    .map((f) => {
      const full = path.join(projectDir, f);
      return { full, mtime: fs.statSync(full).mtimeMs };
    })
    .sort((a, b) => b.mtime - a.mtime);
  return files[0]?.full;
}

// レコードの message.content から「人の発話」と見なせる text ブロックを集める。
// 重要: 1 つの user レコードに <ide_opened_file> 等の自動添付ブロックと本文ブロックが
// 同居することがある（例: [ <ide_opened_file>…, "うまくいきました。一気に" ]）。
// 先頭ブロックだけ見てレコード単位でノイズ判定すると本物のプロンプトを取りこぼすため、
// 必ずブロック単位で判定する（2026-06-11 修正。それまで実プロンプト多数が欠落していた）。
function genuineTextBlocks(rec: RawRecord): string[] {
  const c = rec.message?.content;
  if (typeof c === "string") {
    return isHarnessNoise(c) ? [] : [c];
  }
  const out: string[] = [];
  if (Array.isArray(c)) {
    for (const block of c) {
      if (block && typeof block === "object") {
        const b = block as { type?: string; text?: string };
        if (typeof b.text === "string" && !isHarnessNoise(b.text)) {
          out.push(b.text);
        }
      }
    }
  }
  return out;
}

// ハーネス（CLI/IDE）が自動挿入したラッパー文字列で始まるテキストは、
// 「ユーザーが打った言葉」ではないのでノードから除外する。
// 例: <ide_opened_file> / スラッシュコマンド / /compact の各種出力 / 中断通知 / 継続サマリ。
const NOISE_PREFIXES = [
  "<ide_opened_file>",
  "<ide_selection>",
  "<command-name>",
  "<command-message>",
  "<command-args>",
  "<local-command-caveat>",
  "<local-command-stdout>",
  "<local-command-stderr>",
  "<system-reminder>",
  "[Request interrupted",
  "Caveat: The messages below were generated by the user",
  "This session is being continued from a previous conversation",
];

function isHarnessNoise(text: string): boolean {
  const t = text.trimStart();
  if (t === "") {
    return true;
  }
  return NOISE_PREFIXES.some((p) => t.startsWith(p));
}

// content が tool_result だけ（＝ツール出力の差し戻し、ユーザーの発話ではない）かを判定。
function isOnlyToolResult(rec: RawRecord): boolean {
  const c = rec.message?.content;
  if (!Array.isArray(c) || c.length === 0) {
    return false;
  }
  return c.every(
    (b) => b && typeof b === "object" && (b as { type?: string }).type === "tool_result"
  );
}

export interface LoadResult {
  sessionFile: string;
  nodes: GraphNode[];
}

// 1つの .jsonl をパースし、uuid を持つレコードをファイル内の出現順で返す。
// メタレコード（uuid 無し: mode / queue-operation / last-prompt / file-history-snapshot）は除外。
function parseFileRecords(sessionFile: string): RawRecord[] {
  const content = fs.readFileSync(sessionFile, "utf-8");
  const out: RawRecord[] = [];
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed) {
      continue;
    }
    let d: RawRecord;
    try {
      d = JSON.parse(trimmed);
    } catch {
      continue; // 壊れた行はスキップ
    }
    if (d.uuid) {
      out.push(d);
    }
  }
  return out;
}

// レコードの「内容指紋」。timestamp と組み合わせて canonical key を作る。
// message.content（user/assistant）→ attachment 本体 → system の subtype の順で拾う。
//
// user の発話レコードは「人の発話ブロックの連結」で指紋を取る（2026-06-11）。
// 理由: CLI の resume は履歴を再シリアライズして追記することがあり、その際
// 「自動添付＋本文が同居する 1 レコード」を「別々のレコード」に分割する。
// content 全体の JSON だと同一発話が別指紋になり重複ノード化するため、
// 発話本文だけで同一性を取る（timestamp＋type も鍵に含むので誤統合はしない）。
// 発話ブロックを持たないレコード（tool_result・純粋な自動添付）は従来どおり全 JSON。
function fingerprint(rec: RawRecord): string {
  if (rec.message?.content !== undefined) {
    if (rec.type === "user") {
      const g = genuineTextBlocks(rec);
      if (g.length > 0) {
        return g.join("\n");
      }
    }
    return JSON.stringify(rec.message.content);
  }
  if (rec.attachment !== undefined) {
    return JSON.stringify(rec.attachment);
  }
  if (rec.subtype !== undefined) {
    return rec.subtype;
  }
  return "";
}

// メモ・ピンの永続キー（MVP4）。canonical key を SHA-1 で 16 桁に潰したもの。
// canonical 化と同じ同一性なので、VS Code 再起動・ファイル再読込・Fork 複製をまたいで同じノードに付く。
// 注意: timestamp を持たないレコードは uuid ベースの key になる（recordKey 参照）が、
// そもそもノード化対象はほぼ必ず timestamp を持つので実害はない。
function stableNodeKey(rec: RawRecord): string {
  return crypto.createHash("sha1").update(recordKey(rec)).digest("hex").slice(0, 16);
}

// canonical key = timestamp + type + 内容指紋（S1 §3a）。
// Fork 複製は3つとも完全一致するので畳まれ、手動流用（新しい timestamp）は一致せず分離される。
// timestamp が無いレコードは uuid で一意化し、絶対に畳まない。
function recordKey(rec: RawRecord): string {
  if (!rec.timestamp) {
    return "no-ts|" + rec.uuid;
  }
  return rec.timestamp + "|" + (rec.type ?? "") + "|" + fingerprint(rec);
}

// canonical 化の結果。buildGraphFromRecords にそのまま渡せる形（②③④は不変）。
interface CanonResult {
  recs: Map<string, RawRecord>; // canonicalId → 代表レコード（parentUuid は canonical へ翻訳済み）
  order: string[]; // canonicalId を timestamp 昇順に並べたもの（行・レーン割当の安定化に使う）
  sessionsOf: Map<string, Set<string>>; // canonicalId → 出現セッション集合（クリック先決定に使う）
}

// 複数ファイルを timestamp+内容で正規化し、ファイル間 Fork の複製を1つの canonical ノードへ畳む（S1 §3）。
// 旧実装の「uuid 重複排除」を置き換える中核。uuid は Fork で振り直されるため結合キーに使えない。
//
// 【順序非依存】各レコードの key は (timestamp+type+内容)。Fork コピーは親も一緒に複製され timestamp を保つので、
// 「親 = 親レコードの key」も全ファイルで不変。ゆえに mtime 等の処理順序に一切依存せず正しい DAG が建つ。
// （旧版は「mtime 最古＝オリジナル」と仮定したが、mtime は作成順を表さず幹を誤判定していた。S1 §4 改訂）
//
// 【二次結合】例外として fork 地点の末端 1 件だけは timestamp が再スタンプされ key が一致しない（S1 §10.2）。
// この複製は一次結合の後、安定 ID（promptId / requestId）＋type＋内容＋親 key の一致で併合する（S1 §10.3）。
// export はテスト・検証スクリプトから直接呼べるようにするため（拡張本体は loadProjectAsForest 経由で使う）
export function canonicalize(files: string[]): CanonResult {
  const repOf = new Map<string, RawRecord>(); // key → 代表レコード（最初に見た個体）
  const parentKeyOf = new Map<string, string | null>(); // key → 親レコードの key
  const sessionsOf = new Map<string, Set<string>>(); // key → 出現セッション集合
  const sessionLen = new Map<string, number>(); // sessionId → そのファイルのレコード数（幹の判定に使う）

  // 1st pass: 全ファイルの全レコードを key 化し、親も key で繋ぐ（ファイル内で parentUuid を解決）。
  for (const file of files) {
    const fileRecs = parseFileRecords(file);
    const byUuid = new Map<string, RawRecord>();
    for (const r of fileRecs) {
      byUuid.set(r.uuid!, r);
    }
    for (const rec of fileRecs) {
      const key = recordKey(rec);
      // compact_boundary は parentUuid=null・logicalParentUuid=圧縮前の末尾。
      // logicalParentUuid で橋渡しして DAG の鎖を切らない（/compact 以降がルート化するのを防ぐ）
      const parentUuid = rec.parentUuid ?? rec.logicalParentUuid ?? null;
      const parentRec = parentUuid != null ? byUuid.get(parentUuid) : undefined;
      const pKey = parentRec ? recordKey(parentRec) : null;

      if (!repOf.has(key)) {
        repOf.set(key, rec);
        parentKeyOf.set(key, pKey);
      }
      // 出現セッションを記録
      const sid = rec.sessionId;
      if (sid) {
        const set = sessionsOf.get(key) ?? new Set<string>();
        set.add(sid);
        sessionsOf.set(key, set);
      }
    }
    // このファイル（= 1セッション）のレコード数を控える。
    const sid = fileRecs[0]?.sessionId;
    if (sid) {
      sessionLen.set(sid, Math.max(sessionLen.get(sid) ?? 0, fileRecs.length));
    }
  }

  // ---- 二次結合（S1 §10.3: fork 地点の timestamp 再スタンプ対策）----
  // Fork コピーの末端 1 件は timestamp が Fork 実行時刻に書き換えられるため、
  // 一次 key（timestamp+type+内容）では畳まれず重複ノードになる。
  // ただし安定 ID（user: promptId / assistant: requestId）は再スタンプ後も保存されるので、
  // 「安定 ID・type・内容・親 key がすべて一致し、timestamp だけ違う」key 同士を同一イベントの
  // 複製とみなして併合する。親 key まで一致を要求するのは、安定 ID＋内容が偶然一致しても
  // DAG 上の位置が違えば別イベントだから（誤併合の防止）。
  const aliasOf = new Map<string, string>(); // 併合された key → 代表 key
  {
    const groups = new Map<string, string[]>(); // 安定グループ → 属する key 一覧
    for (const [key, rep] of repOf) {
      // 安定 ID を持つ型だけが対象。attachment / system 等は対象外（安全側に倒す。
      // これらは fork 末端にあっても user ノード化されないので実害がない）
      const stableId =
        rep.type === "user" ? rep.promptId
        : rep.type === "assistant" ? rep.requestId
        : undefined;
      if (!stableId || !rep.timestamp) {
        continue;
      }
      const g =
        stableId + "|" + (rep.type ?? "") + "|" +
        (parentKeyOf.get(key) ?? "<root>") + "|" + fingerprint(rep);
      const arr = groups.get(g) ?? [];
      arr.push(key);
      groups.set(g, arr);
    }
    for (const keys of groups.values()) {
      if (keys.length < 2) {
        continue; // 重複なし＝通常ケース
      }
      // timestamp 最古の key を代表にする。再スタンプは「後の時刻」への書き換えなので、
      // 最古がオリジナルの真の発生時刻。order（timestamp 昇順）の並びも正しくなる。
      keys.sort((a, b) =>
        (repOf.get(a)!.timestamp ?? "").localeCompare(repOf.get(b)!.timestamp ?? "")
      );
      const canon = keys[0];
      for (const k of keys.slice(1)) {
        aliasOf.set(k, canon);
        // 出現セッション集合は代表側へ合流（クリック先の幹選択が複製側のセッションも考慮できるように）
        const into = sessionsOf.get(canon) ?? new Set<string>();
        for (const s of sessionsOf.get(k) ?? []) {
          into.add(s);
        }
        sessionsOf.set(canon, into);
        // 併合した key は canonical 集合から取り除く（以降のループは代表だけを見る）
        repOf.delete(k);
        parentKeyOf.delete(k);
        sessionsOf.delete(k);
      }
    }
  }
  // 親 key の参照が併合済み key を指していたら代表へ付け替えるためのヘルパ。
  // （fork ファイル側の続きレコードは、再スタンプされた末端を親 key として覚えているため）
  const resolveKey = (k: string): string => aliasOf.get(k) ?? k;

  // key → canonicalId（代表レコードの uuid）。これをノード ID とする。
  const canonIdOf = new Map<string, string>();
  for (const [key, rep] of repOf) {
    canonIdOf.set(key, rep.uuid!);
  }

  // クリック先セッション: そのノードを含む中で「最も長く続いたセッション（＝幹）」を選ぶ。
  // mtime ベースの「最古」より正確かつ実用的（共有プレフィックスは本流セッションを開く）。
  const chooseSession = (key: string): string | undefined => {
    const cands = sessionsOf.get(key);
    if (!cands) {
      return undefined;
    }
    let best: string | undefined;
    let bestLen = -1;
    for (const sid of cands) {
      const len = sessionLen.get(sid) ?? 0;
      if (len > bestLen) {
        bestLen = len;
        best = sid;
      }
    }
    return best;
  };

  // 2nd pass: canonical な recs（parentUuid を canonicalId に翻訳・session を確定）を組み立てる。
  const recs = new Map<string, RawRecord>();
  const sessionsById = new Map<string, Set<string>>();
  for (const [key, rep] of repOf) {
    const id = rep.uuid!;
    const pKey = parentKeyOf.get(key) ?? null;
    // 親 key が二次結合で併合されていたら代表 key に解決してから canonicalId へ翻訳する
    const parentCanon = pKey != null ? canonIdOf.get(resolveKey(pKey)) ?? null : null;
    recs.set(id, { ...rep, parentUuid: parentCanon, sessionId: chooseSession(key) });
    sessionsById.set(id, sessionsOf.get(key) ?? new Set());
  }

  // order: timestamp 昇順（信頼できる唯一の時系列）。レーン割当の枝の並びを安定させる。
  const order = [...recs.keys()].sort((a, b) =>
    (recs.get(a)!.timestamp ?? "").localeCompare(recs.get(b)!.timestamp ?? "")
  );

  return { recs, order, sessionsOf: sessionsById };
}

// レコード集合（1ファイルでも複数ファイルのマージでも可）から、
// user レベルの Fork 木／森を組み立てる。MVP1（1木）と MVP1.5（森）の共通コア。
//
// 重要: 入力は canonicalize() で正規化済み（uuid=canonicalId、parentUuid=canonical 親）。
// これにより Type2 Fork（別ファイルへの複製）も「分岐点に子が複数」という形に畳まれ、
// Type1（ファイル内分岐）と同じ仕組みで森が建つ（S1-timestamp-merge-design.md §3）。
function buildGraphFromRecords(
  recs: Map<string, RawRecord>,
  order: string[],
  sessionsOf?: Map<string, Set<string>> // canonicalId → 出現セッション集合（compact 位置の特定に使う）
): GraphNode[] {
  // user 発話ノードだけを抽出（tool_result の差し戻し・ハーネス挿入文は除外）
  const userIds: string[] = [];
  const userSet = new Set<string>();
  for (const id of order) {
    const d = recs.get(id)!;
    if (d.type !== "user") {
      continue;
    }
    // システム挿入（isMeta=true）は人の発話ではないので除外。
    // 「Continue from where you left off.」（VS Code の再開時注入）はテキストの見た目が普通の
    // 発話と区別できないため、プレフィックス判定ではなくこのフラグでしか弾けない
    if (d.isMeta) {
      continue;
    }
    if (isOnlyToolResult(d)) {
      continue;
    }
    // ブロック単位で判定: 自動添付と同居していても、人の発話ブロックが1つでもあればノード化する
    if (genuineTextBlocks(d).length === 0) {
      continue;
    }
    userIds.push(id);
    userSet.add(id);
  }

  // parentUuid を辿って「最も近い user 祖先」を求める
  const nearestUserParent = (id: string): string | null => {
    let p = recs.get(id)?.parentUuid ?? null;
    while (p !== null && p !== undefined) {
      if (userSet.has(p)) {
        return p;
      }
      p = recs.get(p)?.parentUuid ?? null;
    }
    return null;
  };

  // 子マップを作る（DFS とレーン割当に使う）
  const children = new Map<string | null, string[]>();
  const parentOf = new Map<string, string | null>();
  for (const id of userIds) {
    const par = nearestUserParent(id);
    parentOf.set(id, par);
    const arr = children.get(par) ?? [];
    arr.push(id);
    children.set(par, arr);
  }

  // --- /compact の実行位置をエッジへ記録 ---
  // compact_boundary（system レコード）の位置 = 「直近の user 祖先 U と、その後最初の発話」の間。
  // 形は 2 通りある（実データで確認。2026-06-12）:
  //   a) 次の発話が compact 要約レコード経由で boundary にぶら下がる（走査で boundary を跨ぐ）
  //   b) 次の発話が圧縮前の末尾へ直接つながり、boundary＋要約は脇の袋小路になる
  // どちらも「U の子のうち、boundary 以後で最初・かつ boundary と同じセッションに属する子」への
  // 辺が compact を跨ぐ、という一つの規則で特定できる（セッション一致は fork 枝への誤マークを防ぐ）。
  const compactedIds = new Set<string>();
  for (const rec of recs.values()) {
    if (rec.subtype !== "compact_boundary") {
      continue;
    }
    const u = nearestUserParent(rec.uuid!); // null = 履歴の先頭近くで compact した場合（ルート群が対象）
    const kids = (children.get(u) ?? [])
      .slice()
      .sort((a, b) =>
        (recs.get(a)!.timestamp ?? "").localeCompare(recs.get(b)!.timestamp ?? "")
      );
    const bSessions = sessionsOf?.get(rec.uuid!);
    const child = kids.find((k) => {
      if ((recs.get(k)!.timestamp ?? "") < (rec.timestamp ?? "")) {
        return false; // boundary より前の発話は対象外
      }
      const ks = sessionsOf?.get(k);
      if (!bSessions || bSessions.size === 0 || !ks) {
        return true; // セッション情報が無ければ時系列だけで判定（安全側）
      }
      for (const s of ks) {
        if (bSessions.has(s)) {
          return true;
        }
      }
      return false;
    });
    if (child) {
      compactedIds.add(child);
    }
  }

  // --- レーン自動割当（MVP2: 原則A/B / PROTOTYPES.md §2.7）---
  // 原則A: 末端までの深さが最大の子（＝長く続く本流）が親レーンを継ぐ＝親に最も近い。
  // 原則B: 同じ spine から出る枝は、深い row で分岐するものほど内側のレーンに置く。
  //   実装の要: 「本流(primary)の部分木を *先に* 全部割り当ててから、その節の枝を割り当てる」。
  //   こうすると spine の下方（深い row）で分岐した枝が、先に内側のレーン番号を取る
  //   → 浅い位置の枝ほど外側に押し出され、原則Bが自動的に満たされる。

  // 末端までの深さ（leaf=0）。原則A の primary 選択に使う。メモ化。
  const depthCache = new Map<string, number>();
  const subtreeDepth = (id: string): number => {
    const cached = depthCache.get(id);
    if (cached !== undefined) {
      return cached;
    }
    let d = 0;
    for (const c of children.get(id) ?? []) {
      d = Math.max(d, subtreeDepth(c) + 1);
    }
    depthCache.set(id, d);
    return d;
  };

  const lane = new Map<string, number>();
  let nextLane = 0;
  const assign = (id: string, myLane: number) => {
    lane.set(id, myLane);
    const ch = (children.get(id) ?? []).slice();
    if (ch.length === 0) {
      return;
    }
    // 原則A: 深い部分木を持つ子を先頭（本流）に。同深さは元の順序（時系列）を維持（安定ソート）。
    ch.sort((a, b) => subtreeDepth(b) - subtreeDepth(a));
    ch.forEach((cid, i) => {
      // i=0 は本流: 親レーンを継ぎ、その部分木を *先に* 全展開（内側レーンを先取り）。
      // i>=1 は枝: 新レーンを払い出す。
      assign(cid, i === 0 ? myLane : nextLane++);
    });
  };
  // 各ルート（森の木）は出現順（mtime昇順=時系列）に左から並べる。
  const roots = children.get(null) ?? [];
  roots.forEach((rid) => assign(rid, nextLane++));

  // 出力ノード配列（order を保ってグラフ側で row=世代を計算する）
  // prompt は「人の発話ブロック」から取る（自動添付ブロックは表示しない）
  return userIds.map((id) => ({
    id,
    key: stableNodeKey(recs.get(id)!),
    parent: parentOf.get(id) ?? null,
    lane: lane.get(id) ?? 0,
    prompt: genuineTextBlocks(recs.get(id)!).join("\n").trim(),
    session: recs.get(id)!.sessionId,
    timestamp: recs.get(id)!.timestamp,
    compacted: compactedIds.has(id) || undefined,
  }));
}

// 1つの .jsonl を user レベルの Fork 木（ノード配列）へ変換する（MVP1）。
// 単一ファイルでは canonical 化は実質恒等（全 uuid が一意）だが、経路を統一する。
export function loadSessionAsGraph(sessionFile: string): GraphNode[] {
  const { recs, order, sessionsOf } = canonicalize([sessionFile]);
  return buildGraphFromRecords(recs, order, sessionsOf);
}

// プロジェクト内の全 .jsonl を timestamp+内容で正規化し、森（複数木＋セッション間Fork接続）へ
// 変換する（MVP1.5 / S1）。canonicalize は順序非依存なので読み込み順は結果に影響しない。
export function loadProjectAsForest(projectDir: string): {
  sessionFiles: string[];
  nodes: GraphNode[];
} {
  const files = fs
    .readdirSync(projectDir)
    .filter((f) => f.endsWith(".jsonl"))
    .map((f) => {
      const full = path.join(projectDir, f);
      return { full, mtime: fs.statSync(full).mtimeMs };
    })
    .sort((a, b) => a.mtime - b.mtime); // mtime 昇順は表示の安定のためで、DAG 形状には影響しない

  const { recs, order, sessionsOf } = canonicalize(files.map((f) => f.full));
  return {
    sessionFiles: files.map((f) => f.full),
    nodes: buildGraphFromRecords(recs, order, sessionsOf),
  };
}

// チャット（.jsonl）が存在するプロジェクトフォルダの一覧（MVP6 フォルダ選択用）。
export interface ProjectInfo {
  dir: string; // projects/<encoded> の絶対パス
  label: string; // 表示名（実 cwd。読めなければフォルダ名）
  mtime: number; // 最新 .jsonl の mtime（新しい順ソート用）
}

// フォルダ名は encode 済み（非英数字が "-"）で実パスへ確実には戻せないため、
// ラベルは最新 .jsonl の先頭付近のレコードが持つ cwd フィールドから取る。
function projectLabelFor(dir: string, latestFile: string): string {
  try {
    // 先頭 64KB だけ読めば最初の DAG レコード（cwd 持ち）に届く
    const fd = fs.openSync(latestFile, "r");
    const buf = Buffer.alloc(65536);
    const len = fs.readSync(fd, buf, 0, buf.length, 0);
    fs.closeSync(fd);
    for (const line of buf.subarray(0, len).toString("utf-8").split(/\r?\n/)) {
      try {
        const d = JSON.parse(line) as RawRecord & { cwd?: string };
        if (d.cwd) {
          return d.cwd;
        }
      } catch {
        continue; // 末尾の欠け行など
      }
    }
  } catch {
    /* fallthrough */
  }
  return path.basename(dir);
}

// .jsonl を 1 つ以上持つプロジェクトフォルダを、最終更新が新しい順で返す（MVP6）。
export function listProjects(): ProjectInfo[] {
  const root = projectsRoot();
  if (!fs.existsSync(root)) {
    return [];
  }
  const out: ProjectInfo[] = [];
  for (const name of fs.readdirSync(root)) {
    const full = path.join(root, name);
    try {
      if (!fs.statSync(full).isDirectory()) {
        continue;
      }
    } catch {
      continue;
    }
    const latest = latestSessionFile(full);
    if (!latest) {
      continue; // チャットが存在するフォルダのみ
    }
    out.push({
      dir: full,
      label: projectLabelFor(full, latest),
      mtime: fs.statSync(latest).mtimeMs,
    });
  }
  return out.sort((a, b) => b.mtime - a.mtime); // 新しい順
}

// ワークスペースパスから「直近セッションのグラフ」を読み込む高水準 API。
// 見つからなければ undefined（呼び出し側でメッセージ表示）。
export function loadLatestGraphForWorkspace(
  workspacePath: string
): LoadResult | undefined {
  const projectDir = resolveProjectDir(workspacePath);
  if (!projectDir) {
    return undefined;
  }
  const sessionFile = latestSessionFile(projectDir);
  if (!sessionFile) {
    return undefined;
  }
  return { sessionFile, nodes: loadSessionAsGraph(sessionFile) };
}

export interface ForestResult {
  projectDir: string;
  sessionFiles: string[];
  nodes: GraphNode[];
}

// ワークスペースに対応するプロジェクトの「森」を読み込む（MVP1.5 の本線）。
export function loadForestForWorkspace(
  workspacePath: string
): ForestResult | undefined {
  const projectDir = resolveProjectDir(workspacePath);
  if (!projectDir) {
    return undefined;
  }
  const { sessionFiles, nodes } = loadProjectAsForest(projectDir);
  if (sessionFiles.length === 0) {
    return undefined;
  }
  return { projectDir, sessionFiles, nodes };
}

// フォールバック: 直近に活動したプロジェクト（最新 .jsonl を持つフォルダ）の森を読む。
// 開発中にどのフォルダを開いていても森を表示できるようにするため。
export function loadForestAnywhere(): ForestResult | undefined {
  const root = projectsRoot();
  if (!fs.existsSync(root)) {
    return undefined;
  }
  let bestDir: string | undefined;
  let bestMtime = -1;
  for (const dir of fs.readdirSync(root)) {
    const full = path.join(root, dir);
    if (!fs.statSync(full).isDirectory()) {
      continue;
    }
    const latest = latestSessionFile(full);
    if (!latest) {
      continue;
    }
    const mtime = fs.statSync(latest).mtimeMs;
    if (mtime > bestMtime) {
      bestMtime = mtime;
      bestDir = full;
    }
  }
  if (!bestDir) {
    return undefined;
  }
  const { sessionFiles, nodes } = loadProjectAsForest(bestDir);
  return { projectDir: bestDir, sessionFiles, nodes };
}

// フォールバック: 全プロジェクトを横断して、最後に更新された .jsonl を選ぶ。
// （開発中にどのフォルダを開いていても実データを表示できるようにするため）
export function loadLatestGraphAnywhere(): LoadResult | undefined {
  const root = projectsRoot();
  if (!fs.existsSync(root)) {
    return undefined;
  }
  let best: { full: string; mtime: number } | undefined;
  for (const dir of fs.readdirSync(root)) {
    const full = path.join(root, dir);
    if (!fs.statSync(full).isDirectory()) {
      continue;
    }
    const latest = latestSessionFile(full);
    if (!latest) {
      continue;
    }
    const mtime = fs.statSync(latest).mtimeMs;
    if (!best || mtime > best.mtime) {
      best = { full: latest, mtime };
    }
  }
  if (!best) {
    return undefined;
  }
  return { sessionFile: best.full, nodes: loadSessionAsGraph(best.full) };
}
